### ISSUE TITLE
현금영수증 발행 시 clientIp 는 상점관리자에서 어디서 확인가능한가요?

### ISSUE THREAD

**Issue by kyung-yeon** [kginicis-ts/INICIS_Etc#15]
안녕하세요.

![Screenshot 2023-10-18 at 9 13 03 AM](https://github.com/kginicis-ts/INICIS_Etc/assets/39257313/b9ebdb53-85c0-47a3-84ca-cb19cf227639)

1. 현금영수증 발행 시 clientIp 를 전송하고있는데, 상점관리자에서 확인이 가능한가요?
2. 상점관리자에서 확인하는 용도로 사용되고 그 이외에도 사용되는곳이 있는지 궁금합니다.
	* 사용하는곳이 없다면 ip가 아닌 문자열로 남겨두어도 괜찮을까요? 
	  (외부 요청이 아닌 내부 배치작업에 의해 현금영수증 발행 시 문자열을 저장해도 괜찮을지 문의드립니다)

**Comment by ts-inicis** [comment]
1. clientIp 는 상점관리자에서 확인이 불가합니다. 
2. 가맹점 요청에 의한 거래건 추적 용도로만 쓰이며 이외  사용되는 곳은 없습니다.  
    String 타입으로 문자열 설정 가능하나,   가급적 IP 형태로 설정되도록 권장드립니다.
