### ISSUE TITLE
가상계좌 입금통보 테스트 관련 문의

### ISSUE THREAD

**Issue by ksh9891** [kginicis-ts/INICIS_Etc#19]
안녕하세요.
가상계좌 입금통보 테스트 중 문의가 있어 글 남깁니다.

가상계좌 테스트 방법은 아래와 같은 방법으로 알고있습니다.

[입금통보방식 등록]
거래내역 > 거래조회 > 가상계좌 > 입금통보방식선택 메뉴로 이동
입금내역통보방법: 실시간
통보방식: URL 수신
입금내역통보URL 설정

[채번 및 테스트]
개발하고 있는 웹페이지에서 가상계좌 채번작업 수행 > 채번된 정보를 아래 메뉴에 등록
메뉴: 거래내역 > 거래조회 > 가상계좌 > 입금통보테스트

위 같은 절차를 수행하여 테스트를 하려고 하였으나. 
"해당거래가 존재하지 않습니다." 라는 오류가 발생하여 테스트가 진행되지 않습니다.
(가상계좌메뉴의 입금요청조회에 데이터 있는거 확인했습니다.)

의심되는 부분으로는 저희가 사용하는 계정에 상점이 여러개가 존재하는데, 이 부분이 문제가 될 수도 있을까요 ? 

답변 부탁드립니다.

감사합니다.

**Comment by ts-inicis** [comment]
"해당거래가 존재하지 않습니다." 오류는 메시지와 같이 채번 거래건을 찾지 못해 발생되는 경우입니다. 
</br></br>

- 테스트 MID 거래건인 경우
> 테스트 MID 는 자정 이전에 자동으로 취소되므로 익일 이후 입금통보테스트 시 해당되는 거래건을 찾을 수 없어 발생될 수 있습니다. 
</br>

- 채번 TID 에 해당되는 MID 와 상점관리자 로그인 MID 가 상이한 경우
> 동일 MID 로 채번된 내역에만 입금통보테스트를 진행하실 수 있습니다. 
</br>

- 가상계좌 번호 오설정 
> 채번 시 가상계좌번호와 입금통보테스트 진행 시 가상계좌번호가 일치한지 체크 바랍니다. 
</br>

- 특이사항이 없다면 ts@kggroup.co.kr 로 문의 내용과 가상계좌번호 정보를 회신주시면 이력을 확인해 드릴 수 있습니다. 
</br>
